USE [HQTCSDL_BTL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAI_KHOAN] (
	[tai_khoan_id] INT IDENTITY(1,1) PRIMARY KEY,
	[email]	NVARCHAR(100) NOT NULL UNIQUE,
	[mat_khau] NVARCHAR(255) NOT NULL,
	[vai_tro] NVARCHAR(50) NOT NULL
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACH_HANG] (
	[khach_hang_id]	INT IDENTITY(1,1) PRIMARY KEY,
	[tai_khoan_id] INT NOT NULL,
	[ho_ten] NVARCHAR(100) NOT NULL,
	[email]	NVARCHAR(100),
	[so_dien_thoai]	NVARCHAR(20),
	[dia_chi] NVARCHAR(255)
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DANH_MUC] (
	[danh_muc_id] INT IDENTITY(1,1) PRIMARY KEY,
	[ten] NVARCHAR(100) NOT NULL,
	[mo_ta]	NVARCHAR(500)
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SAN_PHAM] (
	[san_pham_id] INT IDENTITY(1,1) PRIMARY KEY,
	[danh_muc_id] INT NOT NULL,
	[ten] NVARCHAR(200) NOT NULL,
	[mo_ta]	NVARCHAR(1000),
	[gia] DECIMAL(18,2) NOT NULL,
	[con_hang] BIT NOT NULL DEFAULT 1,
	[anh] NVARCHAR(500),
	[anh_url] NVARCHAR(500)
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DON_HANG] (
	[don_hang_id] INT IDENTITY(1,1) PRIMARY KEY,
	[khach_hang_id]	INT NOT NULL,
	[ma_don] NVARCHAR(50) NOT NULL UNIQUE,
	[ngay_dat] DATETIME NOT NULL DEFAULT GETDATE(),
	[trang_thai] NVARCHAR(50) NOT NULL,
	[dia_chi_giao] NVARCHAR(255),
	[tong_tien]	DECIMAL(18,2) NOT NULL DEFAULT 0
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GIO_HANG] (
	[gio_hang_id] INT IDENTITY(1,1) PRIMARY KEY,
	[khach_hang_id]	INT NOT NULL,
	[san_pham_id] INT NOT NULL,
	[so_luong] INT NOT NULL DEFAULT 1
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHI_TIET_DON_HANG] (
	[ctdh_id] INT IDENTITY(1,1) PRIMARY KEY,
	[don_hang_id] INT NOT NULL,
	[san_pham_id] INT NOT NULL,
	[so_luong] INT NOT NULL DEFAULT 1,
	[don_gia] DECIMAL(18,2) NOT NULL,
	[ten_san_pham] NVARCHAR(200)
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THANH_TOAN] (
	[thanh_toan_id]	INT IDENTITY(1,1) PRIMARY KEY,
	[don_hang_id] INT NOT NULL,
	[ma_don] NVARCHAR(50),
	[trang_thai] NVARCHAR(50) NOT NULL,
	[phuong_thuc] NVARCHAR(100),
	[tong_tien]	DECIMAL(18,2) NOT NULL,
	[dia_chi_giao] NVARCHAR(255),
	[ngay_dat] DATETIME NOT NULL DEFAULT GETDATE(),
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VAN_CHUYEN] (
	[van_chuyen_id]	INT IDENTITY(1,1) PRIMARY KEY,
	[don_hang_id] INT NOT NULL,
	[don_vi_vc]	NVARCHAR(100),
	[ma_vc_cua_don]	NVARCHAR(100),
	[trang_thai] NVARCHAR(50),
	[ngay_giao_thuc_te]	DATETIME,
	[du_kien_giao] DATETIME
) ON [PRIMARY]
GO

-- Khoa Ngoai
ALTER TABLE [dbo].[KHACH_HANG]
	ADD CONSTRAINT [FK_KHACH_HANG_TAI_KHOAN]
	FOREIGN KEY ([tai_khoan_id]) REFERENCES [dbo].[TAI_KHOAN]([tai_khoan_id])
GO

ALTER TABLE [dbo].[SAN_PHAM]
	ADD CONSTRAINT [FK_SAN_PHAM_DANH_MUC]
	FOREIGN KEY ([danh_muc_id]) REFERENCES [dbo].[DANH_MUC]([danh_muc_id])
GO

ALTER TABLE [dbo].[DON_HANG]
	ADD CONSTRAINT [FK_DON_HANG_KHACH_HANG]
	FOREIGN KEY ([khach_hang_id]) REFERENCES [dbo].[KHACH_HANG]([khach_hang_id])
GO

ALTER TABLE [dbo].[GIO_HANG]
	ADD CONSTRAINT [FK_GIO_HANG_KHACH_HANG]
	FOREIGN KEY ([khach_hang_id]) REFERENCES [dbo].[KHACH_HANG]([khach_hang_id])
GO

ALTER TABLE [dbo].[GIO_HANG]
	ADD CONSTRAINT [FK_GIO_HANG_SAN_PHAM]
	FOREIGN KEY ([san_pham_id]) REFERENCES [dbo].[SAN_PHAM]([san_pham_id])
GO

ALTER TABLE [dbo].[CHI_TIET_DON_HANG]
	ADD CONSTRAINT [FK_CTDH_DON_HANG]
	FOREIGN KEY ([don_hang_id]) REFERENCES [dbo].[DON_HANG]([don_hang_id])
GO

ALTER TABLE [dbo].[CHI_TIET_DON_HANG]
	ADD CONSTRAINT [FK_CTDH_SAN_PHAM]
	FOREIGN KEY ([san_pham_id]) REFERENCES [dbo].[SAN_PHAM]([san_pham_id])
GO

ALTER TABLE [dbo].[THANH_TOAN]
	ADD CONSTRAINT [FK_THANH_TOAN_DON_HANG]
	FOREIGN KEY ([don_hang_id]) REFERENCES [dbo].[DON_HANG]([don_hang_id])
GO

ALTER TABLE [dbo].[VAN_CHUYEN]
	ADD CONSTRAINT [FK_VAN_CHUYEN_DON_HANG]
	FOREIGN KEY ([don_hang_id]) REFERENCES [dbo].[DON_HANG]([don_hang_id])
GO